name: docker-push.yml
on:
  push:
    paths:
        - 'Dockerfile'
        - 'docker-compose.yml'
        - '.github/workflows'
        - 'package.json'
        - 'yarn.lock'
        - '.dockerignore'
        - 'src/**'
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/frigidaire-bot
          tags: |
            type=raw,value={{ date 'YYYYMMDD' }}
            type=sha
            type=raw,value=latest

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
